### ISSUE TITLE
Optimize the result of group by prefix

### ISSUE THREAD

**Issue by mzzsfy** [gejun123456/redispluginIssues#11]
![image](https://user-images.githubusercontent.com/43053461/91278558-f644f580-e7b6-11ea-8d40-965cdf2fc482.png)
I like this feature:redis keys separator support multiple characters

But the result after grouping is very bad

this is my keys
![image](https://user-images.githubusercontent.com/43053461/91279179-c77b4f00-e7b7-11ea-8f1b-25c01a71c77f.png)
use ":" separator 
![image](https://user-images.githubusercontent.com/43053461/91279285-deba3c80-e7b7-11ea-84d7-2504502217c0.png)
More inconvenient than not grouping

I hope this is the result:
![image](https://user-images.githubusercontent.com/43053461/91279645-54bea380-e7b8-11ea-8fc5-91540c79e7c7.png)

**Comment by gejun123456** [comment]
thanks for feedback,  will check it.

**Comment by gejun123456** [comment]
supported.
