### ISSUE TITLE
SSH auth fails

### ISSUE THREAD

**Issue by axelcostaspena** [gejun123456/redispluginIssues#14]
I am trying the plugin, and it always connects fine on localhost, but never connects on hosts which need an SSH tunnel.

Entered same data as in the IDE SSH connections. IDE can connect to SSH shell, to databases through SSH, but Redis client fails to connect to Redis through SSH:

```
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:227)
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:202)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:288)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:258)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:242)
	at org.bruce.tools.nosql.f.a.l.a(l.java:134)
	at org.bruce.tools.nosql.f.a.j.a(j.java:46)
```

**Comment by gejun123456** [comment]
Thanks for feedingback. what is your ssh key format like?  like following.
![image](https://user-images.githubusercontent.com/6340473/94418706-54993580-01b4-11eb-9d43-020afd6ccfc7.png)

**Comment by axelcostaspena** [comment]
Connections are with user+password

**Comment by gejun123456** [comment]
ok, will check it. thanks

**Comment by gejun123456** [comment]
![image](https://user-images.githubusercontent.com/6340473/94444536-00ed1300-01d9-11eb-8c6a-c38dfed65182.png)
just checked, it could work. have you set the ssh user name?

**Comment by axelcostaspena** [comment]
Hi. I did no concrete change, but now it's working.. incredible. Sorry, thank you for your support!
