### ISSUE TITLE
SSH issues

### ISSUE THREAD

**Issue by kevleyski** [gejun123456/redispluginIssues#17]
I'm trying to connect to a remote redis that does not have redis port 6379 open to internet
I can use the regular Deployment feature no problem

If I remove the passphrase from my SSH I can connect to Redis

But with a passphrase in the key I see "Connection test failed"
net.schmizz.sshj.userauth.UserAuthException: Exhasted available authentication methods

help appreciated

**Comment by gejun123456** [comment]
Thanks. current not support ssh with passphrase, will support it in few days.

**Comment by gejun123456** [comment]
[RedisNew-2020.11.27.zip](https://github.com/gejun123456/redispluginIssues/files/5706630/RedisNew-2020.11.27.zip)
supported now， thanks

**Comment by kevleyski** [comment]
Ah great, thanks!
It’s a really useful plugin

**Comment by gejun123456** [comment]
Thanks for helping.
