### ISSUE TITLE
Deleting multiple set values not working

### ISSUE THREAD

**Issue by kevleyski** [gejun123456/redispluginIssues#25]
If highligh select a few items in a set (ordered or. It ordered) if right click to delete it only applies to the value the mouse was clicked on
Have to repeat for each value
Keyboard shortcut also useful here too maybe

**Comment by gejun123456** [comment]
yeah, will support it later, thanks.

**Comment by gejun123456** [comment]
supported

**Comment by kevleyski** [comment]
Thanks again!
