### ISSUE TITLE
未指明RedisTemplate序列化方式时，默认的JdkSerializationRedisSerializer导致key乱码

### ISSUE THREAD

**Issue by nice-buddy** [gejun123456/redispluginIssues#27]
如题，别人的老代码，没有替换RedisTemplate默认的jdk自己的序列化方式JdkSerializationRedisSerializer，导致key都是类似\xac\xed\x00\x05t\x00\x11等开头，但在这个插件中会**乱码**，提示“key does not exist”。

**Comment by gejun123456** [comment]
是的，默认的key编码是utf8 需要给个配置让用户配置下
