### ISSUE TITLE
couldn't connect to redis < 6.0.0

### ISSUE THREAD

**Issue by okhowang** [gejun123456/redispluginIssues#32]
I found redis plugin use `HELLO` command for `AUTH` command.
But it's available from redis 6.0.0.
See https://redis.io/commands/hello

**Comment by okhowang** [comment]
some redis proxy implementation which don't support `HELLO` command will reply `NOAUTH Authentication required.`

**Comment by gejun123456** [comment]
will check it, thanks.

**Comment by gejun123456** [comment]
[RedisNew-2021.03.09.zip](https://github.com/gejun123456/redispluginIssues/files/6114469/RedisNew-2021.03.09.zip)
Fixed，sorry for the delay.
