### ISSUE TITLE
Support shared redis config between project

### ISSUE THREAD

**Issue by okhowang** [gejun123456/redispluginIssues#35]
just like database source has `Global Data Sources` and `Project Data Sources`
![image](https://user-images.githubusercontent.com/3352585/122001297-b224ef00-cde2-11eb-9b6e-cb70766aa157.png)

**Comment by BSVogler** [comment]
I just found out that you can right click an entry and select "Globalize Redis Server"

**Comment by gejun123456** [comment]
supported now.
