### ISSUE TITLE
Support ssl protocol

### ISSUE THREAD

**Issue by BSVogler** [gejun123456/redispluginIssues#39]
Is it possible to use SSL (rediss://)? There is this guide linked for the ssl tunnel, but I don't get where this config file should be.

**Comment by BSVogler** [comment]
The plugin is unusable for me when SSL does not work. Please provide documentation on how to configure this or provide a fix.

**Comment by gejun123456** [comment]
![image](https://user-images.githubusercontent.com/6340473/180640002-7947409f-4396-466f-89a4-6248d10bda9a.png)

**Comment by gejun123456** [comment]
Please help check if it works https://drive.google.com/file/d/1Po9fWGLHycujZMtMT88H8P1fq3V45_aA/view?usp=sharing , Will release the new version in next two days.

**Comment by BSVogler** [comment]
It looks like it works. Thanks. Will get this now for my whole team.

**Comment by gejun123456** [comment]
Thanks alot for feedback.
