### ISSUE TITLE
Console Play button menu is grayed out

### ISSUE THREAD

**Issue by JoshuaHintze** [gejun123456/redispluginIssues#41]
Not sure why this is happening. 

![image](https://user-images.githubusercontent.com/7818200/164755805-b8bfce3c-67ae-4ef2-bf15-a68c353a1dc1.png)

Clicking on the Play button shows a grayed out menu

![image](https://user-images.githubusercontent.com/7818200/164755859-c1d8347d-8bcb-4dcf-9f4f-7a28028dd030.png)

I am connected to the redis server. I can browse the keys and create them, it's just the console doesn't allow me to run any commands.

![image](https://user-images.githubusercontent.com/7818200/164755933-afb2ad55-1c5a-4c38-85c2-3636dc3905e3.png)

![image](https://user-images.githubusercontent.com/7818200/164755976-0f87e456-79b4-418e-869a-8b9a1e8d626f.png)

**Comment by gejun123456** [comment]
Thanks for reporting,  could you update the plugin to the newest version to check if it work.

**Comment by JoshuaHintze** [comment]
@gejun123456  - I haven't seen a new version prompt in php storm yet. Does it take a while for updates to get approved by Jet Brains?

**Comment by gejun123456** [comment]
Sorry, my mistake, you are using the newest version now, will check it later.

**Comment by gejun123456** [comment]
I got the same in phpStorm, will try to fix it soon.

**Comment by JoshuaHintze** [comment]
Great. Thank you

**Comment by gejun123456** [comment]
After check, phpstorm doesn't support.   will add a right click action to execute command.
![image](https://user-images.githubusercontent.com/6340473/170817941-c519501a-c3bb-4040-824c-42f61ad98190.png)
will release in next week.
Thanks for helping.

**Comment by JoshuaHintze** [comment]
Thank you.

**Comment by JoshuaHintze** [comment]
This looks to be fixed. Thanks.
