### ISSUE TITLE
Log4j dependency version vulnerabilities

### ISSUE THREAD

**Issue by alvarorodriguezestruch** [gejun123456/redispluginIssues#52]
Hi, log4j dependency have lot of vulnerabilities on versions 1.X as you can see (https://www.cvedetails.com/vulnerability-list/vendor_id-45/product_id-37215/Apache-Log4j.html). 

Do you have any plan to update this dependency to a later version?

**Comment by gejun123456** [comment]
thanks for reporting [RedisNew-2023.04.14.zip](https://github.com/gejun123456/redispluginIssues/files/11232750/RedisNew-2023.04.14.zip) will fix the issue.

**Comment by gejun123456** [comment]
fixed
