### ISSUE TITLE
The plugin UI does not appear with the new jetbrains UI.

### ISSUE THREAD

**Issue by hojabri** [gejun123456/redispluginIssues#54]
When enabling the new UI, the plugin interface is not shown in the window.
<img width="55" alt="Screenshot 2023-04-14 at 16 01 21" src="https://user-images.githubusercontent.com/15908565/232066241-4ce2b13f-cb01-4ab4-858f-83bade550db3.png">

**Comment by gejun123456** [comment]
will check it soon.

**Comment by gejun123456** [comment]
![image](https://user-images.githubusercontent.com/6340473/232178188-d5cec41c-f3f8-494c-808a-6a4a2d5f1d4f.png)

![image](https://user-images.githubusercontent.com/6340473/232178197-cadbea45-eb5e-464c-b8f3-874b01f173ca.png)
seem works for me in new ui, could you help check if plugin is enabled.

**Comment by gejun123456** [comment]
i'm using with intellij, could you share about your enviroment.

**Comment by hojabri** [comment]
Hey,
Thank you, yes, your solution solved my problem. 👍
