### ISSUE TITLE
Despite installing, Unable to locate /use  in IntelliJ IDEA 2023.1.2 (Ultimate Edition)

### ISSUE THREAD

**Issue by neerajgupta2407** [gejun123456/redispluginIssues#55]
Hi

I have instlled the Redis client in  IntelliJ IDEA 2023.1.2 (Ultimate Edition), but i am unable to locate or use.

Plugin is installed in plugin manager.
<img width="1367" alt="Screenshot 2023-06-03 at 11 22 16 AM" src="https://github.com/gejun123456/redispluginIssues/assets/2323163/36343fc1-4eb7-41ab-823b-764de92e7e4e">

**Comment by gejun123456** [comment]
![image](https://github.com/gejun123456/redispluginIssues/assets/6340473/6b37dee8-63b5-48a7-a1b7-3815b09a148d)
could you find it in the menu.
