### ISSUE TITLE
Redis plugin not working on IntelliJ IDEA 2020.1.1 (Ultimate Edition)

### ISSUE THREAD

**Issue by petrutbeleleu** [gejun123456/redispluginIssues#6]
"Test connection" button ignores values from input fields and always return the popup with the message "Connection test successful to RedisDB", even if all fields are empty.

**Comment by gejun123456** [comment]
wil check it, thanks.

**Comment by gejun123456** [comment]
[RedisNew-2020.06.14.zip](https://github.com/gejun123456/redispluginIssues/files/4761796/RedisNew-2020.06.14.zip)
Fixed, sorry for the delay, will upload to jetbrain market today.

Thanks.
